### ISSUE TITLE
Error parsing csv file

### ISSUE THREAD

**Issue by cwagar** [TablePlus/TableTool-issue-tracker#1]
The following csv file throws an error when loading. It's likely the csv file is indeed not clean, however it's produced by a workflow which is not likely easy to be changed (US Government reporting data).

The file is successfully parsed and opened by another app (Easy CSV Editor).

Direct link: https://nces.ed.gov/ipeds/datacenter/data/HD2022.zip
Context: https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx?gotoReportId=7&fromIpeds=true&sid=3356bec1-9a62-4cae-86b6-666647cc452d&rtid=7

Issue reported: Method to express ignore_errors flag to underlying csv engine needed

Thank you

Error
----
Invalid Input Error: CSV Error on Line: 93
Original Line: 
105297,"Dine College"," ","Route 12, One Circle Drive","Tsaile","AZ","86556", 4, 6,"Charles Monty Roessel","President","9287246600","860215931","KAAMMFK1JJL8","00824600",1,"https://www.dinecollege.edu/","https://www.dinecollege.edu/admissions/admissions/","https://www.dinecollege.edu/admissions/financial-aid/","https://www.dinecollege.edu/admissions/admissions","www.dinecollege.edu/net-price-calculator/"," ","https://www.dinecollege.edu/admissions/student-right-to-know-act/","https://www.dinecollege.edu/admissions/student-services/",1,1,1,7,1,1,20,1,2,2,2,1,43,1,"A ",-2,-2,"-2",1,1,1,1,1,3,33,9,0,5,2,6,33,33,33,60,1,2,2,"-2","-2",-2,-2,-2,4001,"Apache County",401,-109.216840,36.293328,172,2
Invalid unicode (byte sequence mismatch) detected.

Possible Solution: Enable ignore errors (ignore_errors=true) to skip this row

file=/Users/clayton/Downloads/IPEDS23/hd2022.csv
delimiter = , (Auto-Detected)
quote = " (Auto-Detected)
escape = \0 (Auto-Detected)
new_line = Single-Line File (Auto-Detected)
header = false (Auto-Detected)
skip_rows = 0 (Auto-Detected)
date_format =  (Auto-Detected)
timestamp_format =  (Auto-Detected)
null_padding=0
sample_size=20480
ignore_errors=false
all_varchar=0

**Comment by huyphams** [comment]
We will add an advanced settings where you can choose the CSV import option in the TableTool. and also ingore_errors too. Thanks for the feedback

**Comment by huyphams** [comment]
We've added the advanced option, include the ignore error!
